pipeline {
  agent any

  environment {
    IMAGE_NAME = "demo-flask:${env.BUILD_NUMBER}"
  }

  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build image') {
      steps {
        script {
          sh 'docker build -t $IMAGE_NAME .'
        }
      }
    }

    stage('Test') {
      steps {
        sh '''
          docker run --rm $IMAGE_NAME /bin/sh -c "pytest -q"
        '''
      }
    }

    stage('Run (Deploy)') {
      steps {
        sh '''
          docker rm -f demo-flask-running || true
          docker run -d --name demo-flask-running -p 5000:5000 $IMAGE_NAME
        '''
      }
    }
  }

  post {
    always {
      echo "Build finished. You can view app at http://<jenkins-host>:5000"
    }
    failure {
      echo "Build failed"
    }
  }
}
